import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FiActivity, FiDollarSign, FiEdit3, FiInfo, FiPieChart, FiSave, FiTarget, FiTrendingUp, FiUsers, FiX } from "react-icons/fi";
import KpiCard from "./KpiCard";
import { normalizeInvestorMetrics, useInvestorMetrics } from "../hooks/useInvestorMetrics";

const CARD_CLASS = "rounded-3xl border border-slate-200 bg-white p-6 shadow-sm";
const FORM_SECTIONS = {
  coreFinancials: [
    { key: "revenue", label: "Revenue", suffix: "(INR)", tooltip: "Total money earned after discounts, before expenses." },
    { key: "gmv", label: "GMV", suffix: "(INR)", tooltip: "Gross Merchandise Value: total value of all orders processed before commissions or cuts." },
    { key: "arrr", label: "ARRR", suffix: "(INR)", tooltip: "Annualized Revenue Run Rate based on recent performance extrapolated over a full year." },
    { key: "cogs", label: "COGS", suffix: "(INR)", tooltip: "Direct costs tied to delivering the service, such as labor, detergent, and delivery." },
  ],
  unitEconomics: [
    { key: "opex", label: "OPEX", suffix: "(INR)", tooltip: "Operating expenses such as salaries, rent, software, and other overhead." },
    { key: "cac", label: "CAC", suffix: "(INR)", tooltip: "Customer Acquisition Cost: average cost to acquire one new customer." },
    { key: "clv", label: "CLV", suffix: "(INR)", tooltip: "Customer Lifetime Value: estimated revenue generated by one customer over their full relationship with the company." },
  ],
  fundraising: [
    { key: "valuation", label: "Valuation", suffix: "(INR)", tooltip: "Pre-money company valuation before the current raise is invested." },
    { key: "targetRaise", label: "Target Raise", suffix: "(INR)", tooltip: "Total amount the company plans to raise in this fundraising round." },
    { key: "liabilities", label: "Liabilities", suffix: "(INR)", tooltip: "Existing debt or payment obligations currently owed by the company." },
  ],
};

const formatINR = (val, type = "currency") => {
  if (type === "percent") return `${val}%`;
  if (type === "text") return val;
  if (val >= 10000000) return `Rs ${(val / 10000000).toFixed(2)} Cr`;
  if (val >= 100000) return `Rs ${(val / 100000).toFixed(2)} L`;
  if (val >= 1000) return `Rs ${(val / 1000).toFixed(1)} k`;
  return `Rs ${val}`;
};

function LabelWithInfo({ text, tooltip }) {
  return (
    <div className="flex w-full items-center gap-1.5">
      <span className="truncate">{text}</span>
      <span className="group relative inline-flex flex-shrink-0 cursor-help items-center">
        <FiInfo className="text-slate-400 transition-colors hover:text-blue-500" size={13} />
        <span className="pointer-events-none invisible absolute bottom-full left-1/2 z-50 mb-2 w-56 -translate-x-1/2 whitespace-normal rounded-lg bg-slate-800 p-2.5 text-center text-xs font-medium leading-relaxed text-white opacity-0 shadow-xl transition-all normal-case tracking-normal group-hover:visible group-hover:opacity-100">
          {tooltip}
          <span className="absolute left-1/2 top-full -mt-1 -translate-x-1/2 border-4 border-transparent border-t-slate-800" />
        </span>
      </span>
    </div>
  );
}

function MetricDetail({ label, value, tooltip, tone = "default" }) {
  const toneClass = tone === "danger" ? "text-rose-600" : "text-slate-900";

  return (
    <div className="rounded-2xl bg-slate-50 px-4 py-3">
      <div className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">
        {tooltip ? <LabelWithInfo text={label} tooltip={tooltip} /> : label}
      </div>
      <p className={`mt-2 text-lg font-extrabold tracking-tight ${toneClass}`}>{value}</p>
    </div>
  );
}

function FormLabel({ label, suffix = "", tooltip }) {
  return (
    <div className="mb-1.5 text-xs font-bold uppercase text-slate-500">
      <LabelWithInfo text={`${label} ${suffix}`.trim()} tooltip={tooltip} />
    </div>
  );
}

function DerivedMetricPreview({ label, value, tooltip }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3">
      <div className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">
        <LabelWithInfo text={label} tooltip={tooltip} />
      </div>
      <p className="mt-2 text-lg font-extrabold tracking-tight text-slate-950">{value}</p>
    </div>
  );
}

export default function InvestorMetrics() {
  const { metrics, loading, saveMetrics, isSaving } = useInvestorMetrics();
  const [isEditing, setIsEditing] = useState(false);
  const [formData, setFormData] = useState({});
  const [isChartReady, setIsChartReady] = useState(false);

  useEffect(() => {
    const frameId = window.requestAnimationFrame(() => setIsChartReady(true));
    return () => window.cancelAnimationFrame(frameId);
  }, []);

  const draftMetrics = useMemo(
    () => normalizeInvestorMetrics(formData.chartData ? formData : metrics),
    [formData, metrics]
  );

  if (loading) {
    return (
      <div className="flex h-64 w-full items-center justify-center">
        <p className="animate-pulse text-sm font-bold uppercase tracking-widest text-slate-500">Loading Financials...</p>
      </div>
    );
  }

  const handleEditClick = () => {
    setFormData(JSON.parse(JSON.stringify(metrics)));
    setIsEditing(true);
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: name === "instrument" ? value : Number(value),
    }));
  };

  const handleChartPointChange = (index, key, value) => {
    setFormData((prev) => {
      const nextChartData = [...(prev.chartData || [])];
      nextChartData[index] = {
        ...nextChartData[index],
        [key]: key === "month" ? value : Number(value),
      };

      return {
        ...prev,
        chartData: nextChartData,
      };
    });
  };

  const handleSave = async () => {
    const success = await saveMetrics(formData);
    if (success) setIsEditing(false);
  };

  if (isEditing) {
    return (
      <div className="animate-fade-in rounded-3xl border border-slate-200 bg-white p-8 shadow-sm" style={{ fontFamily: "DM Sans, sans-serif" }}>
        <div className="mb-8 flex items-center justify-between border-b border-slate-100 pb-5">
          <div>
            <h2 className="text-2xl font-extrabold text-slate-950">Update Dashboard Data</h2>
            <p className="mt-1 text-sm text-slate-500">Enter raw numbers and the dashboard will calculate margin, EBITDA, and chart output instantly.</p>
          </div>
          <div className="flex gap-3">
            <button onClick={() => setIsEditing(false)} className="flex items-center gap-2 rounded-xl bg-slate-100 px-5 py-2.5 font-bold text-slate-600 transition-colors hover:bg-slate-200">
              <FiX size={18} /> Cancel
            </button>
            <button onClick={handleSave} disabled={isSaving} className="flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 font-bold text-white shadow-md shadow-blue-500/20 transition-colors hover:bg-blue-700 disabled:opacity-50">
              <FiSave size={18} /> {isSaving ? "Saving..." : "Save Data"}
            </button>
          </div>
        </div>

        <div className="mb-8 grid grid-cols-1 gap-4 md:grid-cols-2">
          <DerivedMetricPreview label="Auto Gross Margin" tooltip="Calculated as (Revenue - COGS) / Revenue x 100." value={formatINR(draftMetrics.marginPct, "percent")} />
          <DerivedMetricPreview label="Auto EBITDA" tooltip="Calculated as Revenue - COGS - OPEX." value={formatINR(draftMetrics.ebitda)} />
        </div>

        <div className="grid grid-cols-1 gap-10 md:grid-cols-3">
          <div className="space-y-5">
            <h3 className="border-b pb-2 text-xs font-bold uppercase tracking-wider text-slate-800">Core Financials</h3>
            {FORM_SECTIONS.coreFinancials.map((field) => (
              <div key={field.key}>
                <FormLabel label={field.label} suffix={field.suffix} tooltip={field.tooltip} />
                <input type="number" name={field.key} value={formData[field.key]} onChange={handleInputChange} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
              </div>
            ))}
          </div>

          <div className="space-y-5">
            <h3 className="border-b pb-2 text-xs font-bold uppercase tracking-wider text-slate-800">Unit Economics</h3>
            {FORM_SECTIONS.unitEconomics.map((field) => (
              <div key={field.key}>
                <FormLabel label={field.label} suffix={field.suffix} tooltip={field.tooltip} />
                <input type="number" name={field.key} value={formData[field.key]} onChange={handleInputChange} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
              </div>
            ))}
          </div>

          <div className="space-y-5">
            <h3 className="border-b pb-2 text-xs font-bold uppercase tracking-wider text-slate-800">Fundraising & Cap Table</h3>
            {FORM_SECTIONS.fundraising.map((field) => (
              <div key={field.key}>
                <FormLabel label={field.label} suffix={field.suffix} tooltip={field.tooltip} />
                <input type="number" name={field.key} value={formData[field.key]} onChange={handleInputChange} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
              </div>
            ))}
            <div>
              <FormLabel label="Instrument Type" tooltip="The legal structure of the investment, such as equity, SAFE, or convertible debt." />
              <input type="text" name="instrument" value={formData.instrument} onChange={handleInputChange} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <FormLabel label="Founder" suffix="(%)" tooltip="Percentage of total company equity currently held by founders." />
                <input type="number" name="founderEquity" value={formData.founderEquity} onChange={handleInputChange} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
              </div>
              <div>
                <FormLabel label="Investors" suffix="(%)" tooltip="Percentage of total company equity currently owned by outside investors." />
                <input type="number" name="seedInvestors" value={formData.seedInvestors} onChange={handleInputChange} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
              </div>
            </div>
          </div>
        </div>

        <div className="mt-10 rounded-3xl border border-slate-200 bg-slate-50/70 p-6">
          <div className="mb-5">
            <p className="text-sm font-bold uppercase tracking-[0.22em] text-slate-500">Growth vs Cash Burn</p>
            <h3 className="mt-1 text-xl font-extrabold tracking-tight text-slate-950">Edit the last 5 months</h3>
          </div>

          <div className="grid grid-cols-1 gap-4 xl:grid-cols-5">
            {formData.chartData?.map((point, index) => (
              <div key={`${point.month}-${index}`} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
                <div className="mb-3">
                  <FormLabel label="Month" tooltip="Short label used on the chart x-axis, such as Jan, Feb, or Mar." />
                  <input type="text" value={point.month} onChange={(e) => handleChartPointChange(index, "month", e.target.value)} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
                </div>
                <div className="mb-3">
                  <FormLabel label="Revenue" suffix="(INR)" tooltip="Revenue for this month used in the growth chart." />
                  <input type="number" value={point.revenue} onChange={(e) => handleChartPointChange(index, "revenue", e.target.value)} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
                </div>
                <div>
                  <FormLabel label="Cash Burn" suffix="(INR)" tooltip="Net monthly burn used in the comparison chart." />
                  <input type="number" value={point.cashBurn} onChange={(e) => handleChartPointChange(index, "cashBurn", e.target.value)} className="w-full rounded-xl border border-slate-300 p-3 font-semibold outline-none transition-all focus:ring-2 focus:ring-blue-500" />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="animate-fade-in space-y-8" style={{ fontFamily: "DM Sans, sans-serif" }}>
      <section>
        <div className="mb-4 flex items-center justify-between">
          <div>
            <p className="text-sm font-bold uppercase tracking-[0.22em] text-slate-500">Core Financials</p>
            <h2 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">Headline performance</h2>
          </div>
          <button onClick={handleEditClick} className="flex items-center gap-2 rounded-xl bg-blue-50 px-4 py-2 text-sm font-bold text-blue-600 transition-colors hover:bg-blue-100">
            <FiEdit3 size={16} /> Edit Data
          </button>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-4">
          <KpiCard label={<LabelWithInfo text="Revenue" tooltip="Total money earned after discounts, before expenses" />} value={formatINR(metrics.revenue)} icon={FiDollarSign} color="blue" />
          <KpiCard label={<LabelWithInfo text="GMV" tooltip="Gross Merchandise Value: Total value of all orders processed before commission or cuts" />} value={formatINR(metrics.gmv)} icon={FiActivity} color="purple" />
          <KpiCard label={<LabelWithInfo text="ARRR" tooltip="Annualized Revenue Run Rate: Calculated as the recent revenue trend extrapolated over 12 months" />} value={formatINR(metrics.arrr)} icon={FiTrendingUp} color="green" />
          <KpiCard label={<LabelWithInfo text="Gross Margin" tooltip="Auto-calculated from Revenue and COGS to reduce manual math errors" />} value={formatINR(metrics.marginPct, "percent")} icon={FiPieChart} color="amber" />
        </div>
      </section>

      <section className={CARD_CLASS}>
        <div className="mb-6">
          <p className="text-sm font-bold uppercase tracking-[0.22em] text-slate-500">Growth vs Cash Burn</p>
          <h2 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">Revenue scaling ahead of burn</h2>
        </div>
        <div className="h-[320px] w-full min-w-0">
          {isChartReady && (
            <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={1}>
              <AreaChart data={metrics.chartData} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}>
                <defs>
                  <linearGradient id="revenueGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#2563EB" stopOpacity={0.35} />
                    <stop offset="95%" stopColor="#2563EB" stopOpacity={0.03} />
                  </linearGradient>
                  <linearGradient id="burnGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#DC2626" stopOpacity={0.3} />
                    <stop offset="95%" stopColor="#DC2626" stopOpacity={0.03} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#CBD5E1" vertical={false} />
                <XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: "#64748B", fontSize: 12 }} />
                <YAxis tickFormatter={(value) => `Rs ${value >= 100000 ? `${(value / 100000).toFixed(1)}L` : `${(value / 1000).toFixed(0)}k`}`} tickLine={false} axisLine={false} tick={{ fill: "#64748B", fontSize: 12 }} />
                <Tooltip formatter={(value) => [`Rs ${new Intl.NumberFormat("en-IN").format(value)}`, undefined]} contentStyle={{ borderRadius: "16px", border: "1px solid #E2E8F0", boxShadow: "0 10px 30px rgba(15, 23, 42, 0.08)" }} />
                <Legend />
                <Area type="monotone" dataKey="revenue" name="Revenue" stroke="#2563EB" fill="url(#revenueGradient)" strokeWidth={3} />
                <Area type="monotone" dataKey="cashBurn" name="Cash Burn" stroke="#DC2626" fill="url(#burnGradient)" strokeWidth={3} />
              </AreaChart>
            </ResponsiveContainer>
          )}
        </div>
      </section>

      <section>
        <div className="mb-4">
          <p className="text-sm font-bold uppercase tracking-[0.22em] text-slate-500">Unit Economics</p>
          <h2 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">Efficiency at scale</h2>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">
          <KpiCard label={<LabelWithInfo text="EBITDA" tooltip="Auto-calculated as Revenue minus COGS minus OPEX" />} value={formatINR(metrics.ebitda)} icon={FiDollarSign} color="blue" />
          <KpiCard label={<LabelWithInfo text="CAC" tooltip="Customer Acquisition Cost: total marketing and sales spend per new customer" />} value={formatINR(metrics.cac)} icon={FiUsers} color="red" />
          <KpiCard label={<LabelWithInfo text="CLV" tooltip="Customer Lifetime Value: estimated revenue from a customer over the full relationship" />} value={formatINR(metrics.clv)} icon={FiTarget} color="green" />
        </div>
      </section>

      <section className="grid grid-cols-1 gap-6 xl:grid-cols-2">
        <div className={CARD_CLASS}>
          <p className="text-sm font-bold uppercase tracking-[0.22em] text-slate-500">Fundraising Targets</p>
          <h2 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">Round structure</h2>
          <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
            <MetricDetail label="Pre-money Valuation" tooltip="Company value agreed upon prior to new investment" value={formatINR(metrics.valuation)} />
            <MetricDetail label="Target Raise" tooltip="Total amount of funding the company is looking to secure" value={formatINR(metrics.targetRaise)} />
            <MetricDetail label="Instrument Type" tooltip="The legal structure of the investment, such as equity, SAFE, or convertible debt" value={metrics.instrument} />
            <MetricDetail label="Existing Liabilities" tooltip="Total outstanding debt or payment obligations currently owed by the company" value={formatINR(metrics.liabilities)} tone="danger" />
          </div>
        </div>

        <div className={CARD_CLASS}>
          <p className="text-sm font-bold uppercase tracking-[0.22em] text-slate-500">Cap Table</p>
          <h2 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">Current ownership mix</h2>
          <div className="mt-8 space-y-6">
            <div className="mb-2 flex items-center justify-between text-sm font-semibold text-slate-700">
              <span className="flex items-center gap-1.5">Founder Equity <FiInfo className="text-slate-400" size={13} title="Total percentage owned by founders" /></span>
              <span>{metrics.founderEquity}%</span>
            </div>
            <div className="-mt-4 h-3 overflow-hidden rounded-full bg-slate-200">
              <div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-400" style={{ width: `${metrics.founderEquity}%` }} />
            </div>

            <div className="mb-2 mt-6 flex items-center justify-between text-sm font-semibold text-slate-700">
              <span className="flex items-center gap-1.5">Seed Investors <FiInfo className="text-slate-400" size={13} title="Total percentage owned by external investors" /></span>
              <span>{metrics.seedInvestors}%</span>
            </div>
            <div className="-mt-4 h-3 overflow-hidden rounded-full bg-slate-200">
              <div className="h-full rounded-full bg-gradient-to-r from-amber-400 to-orange-500" style={{ width: `${metrics.seedInvestors}%` }} />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
